workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Build debug APK
        script: |
          set -euxo pipefail
          # Se il wrapper non esiste, crealo
          if [ ! -f "./gradlew" ]; then
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.7
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x gradlew

          # Info di diagnostica
          ./gradlew --version

          # Compila l'app (modulo :app)
          ./gradlew clean :app:assembleDebug --stacktrace --no-daemon
    artifacts:
      - app/build/outputs/apk/debug/*.apk
