workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_SDK_ROOT: /opt/android-sdk-linux
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Build debug APK
        script: |
          chmod +x ./gradlew
          ./gradlew clean assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/apk/debug/*.apk
