workflows:
  android_debug:
    name: Android Debug (FREE, no cache)
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.plutoo.app"
      java: 17
    # ⚠️ Nessuna cache: evitiamo attese infinite su "Restoring cache"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    scripts:
      - name: Install Gradle 8.5
        script: |
          echo "Installing Gradle 8.5 via SDKMAN"
          sdk install gradle 8.5 || sdk use gradle 8.5
          gradle -v

      - name: Gradle dependencies (no cache)
        script: |
          echo "Clean & buildEnvironment (no build cache)"
          gradle --no-daemon --no-build-cache --stacktrace clean
          gradle --no-daemon --no-build-cache --stacktrace buildEnvironment

      - name: Build debug APK
        script: |
          echo "Assemble debug APK (no build cache)"
          gradle --no-daemon --no-build-cache --stacktrace assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
