workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 60
    instance_type: linux
    environment:
      java: 17
    scripts:
      - name: Installa Gradle 8.7
        script: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle --version
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug || ./gradlew build
    artifacts:
      - app/build/outputs/apk/debug/*.apk
