workflows:
  android_debug:
    name: Android Debug (WebView + AdMob)
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.plutoo.app"
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    scripts:
      # STEP 1: Installa Gradle "globale" e verifica
      - name: Install Gradle 8.7
        script: |
          echo "Installing Gradle 8.7 via SDKMAN"
          sdk install gradle 8.7 || sdk use gradle 8.7
          gradle -v

      # STEP 2: Sincronizza dipendenze e pulizia usando 'gradle' (NON il wrapper)
      - name: Gradle dependencies
        script: |
          echo "Sync and clean with plain Gradle"
          gradle --no-daemon --stacktrace clean
          gradle --no-daemon --stacktrace buildEnvironment

      # STEP 3: Build APK debug con 'gradle'
      - name: Build debug APK
        script: |
          echo "Assemble debug with plain Gradle"
          gradle --no-daemon --stacktrace assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/mapping.txt

    publishing:
      email:
        recipients:
          - your@email.here
        notify:
          success: true
          failure: true
