workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Build debug APK
        script: |
          set -euo pipefail

          # 1) Se non c'è il wrapper, scarica Gradle "ufficiale" e crealo
          if [ ! -f "./gradlew" ]; then
            echo "Gradle wrapper assente: scarico Gradle 8.7 e genero il wrapper..."
            curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
            unzip -q gradle.zip
            ./gradle-8.7/bin/gradle wrapper --gradle-version 8.7
          fi

          # 2) Usa sempre il wrapper
          chmod +x gradlew
          ./gradlew --version

          # 3) Build
          ./gradlew clean :app:assembleDebug --stacktrace --no-daemon
    artifacts:
      - app/build/outputs/apk/debug/*.apk
