workflows:
  android_debug:
    name: Android Debug (WebView + AdMob)
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.plutoo.app"
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      # STEP 1: Install Gradle and create wrapper locally
      - name: Prepare Gradle
        script: |
          echo "Installing Gradle 8.7"
          sdk install gradle 8.7 || true
          echo "Creating Gradle wrapper"
          gradle wrapper --gradle-version 8.7
          chmod +x ./gradlew
          echo "Gradle wrapper created successfully!"

      # STEP 2: Sync dependencies and clean project
      - name: Gradle dependencies
        script: |
          echo "Running dependency sync..."
          ./gradlew clean --no-daemon
          ./gradlew buildEnvironment --no-daemon

      # STEP 3: Build debug APK
      - name: Build debug APK
        script: |
          echo "Building debug APK..."
          ./gradlew assembleDebug --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/mapping.txt

    publishing:
      email:
        recipients:
          - your@email.here
        notify:
          success: true
          failure: true
