workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_SDK_ROOT: /opt/android-sdk-linux
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Ensure Gradle wrapper
        script: |
          if [ ! -f "./gradlew" ]; then
            echo "Gradle wrapper not found. Installing..."
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.7
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x gradlew
      - name: Build debug APK
        script: |
          ./gradlew clean assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/apk/debug/*.apk
