name: Android Release APK — build & sign (GitHub Actions only)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # ---------- Android SDK: install + path CORRETTO ----------
      - name: Set up Android SDK (manual install)
        shell: bash
        run: |
          set -e
          sudo apt-get update -y
          sudo apt-get install -y wget unzip
          ANDROID="$HOME/android-sdk"
          mkdir -p "$ANDROID/cmdline-tools"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O /tmp/cmdline-tools.zip
          unzip -q /tmp/cmdline-tools.zip -d "$ANDROID/cmdline-tools"
          # lo zip crea ANDROID/cmdline-tools/cmdline-tools/... -> spostiamo in "latest"
          mv "$ANDROID/cmdline-tools/cmdline-tools" "$ANDROID/cmdline-tools/latest"

          echo "ANDROID_HOME=$ANDROID"        >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID"    >> $GITHUB_ENV
          echo "$ANDROID/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID/platform-tools"            >> $GITHUB_PATH

          yes | "$ANDROID/cmdline-tools/latest/bin/sdkmanager" --licenses
          yes | "$ANDROID/cmdline-tools/latest/bin/sdkmanager" --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # ---------- Keystore dai secret ----------
      - name: Recreate keystore from base64
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > keystore.jks
          ls -l keystore.jks

      # ---------- Build APK non firmato ----------
      - name: Assemble release (unsigned)
        run: ./gradlew assembleRelease --stacktrace

      # ---------- Trova APK non firmato ----------
      - name: Find unsigned APK
        id: find_apk
        run: |
          APK_PATH=$(ls -1 app/build/outputs/apk/release/*-release-unsigned.apk | head -n 1 || true)
          if [ -z "$APK_PATH" ]; then
            echo "Unsigned APK non trovato. File presenti:"
            find app/build/outputs -type f -print
            exit 1
          fi
          echo "apk=$APK_PATH" >> $GITHUB_OUTPUT
          echo "Trovato: $APK_PATH"

      # ---------- zipalign + firma ----------
      - name: Zipalign & Sign APK
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          set -e
          UNSIGNED="${{ steps.find_apk.outputs.apk }}"
          ALIGNED="app-release-aligned.apk"
          SIGNED="Plutoo-release-signed.apk"

          "$ANDROID_HOME/build-tools/34.0.0/zipalign" -v -p 4 "$UNSIGNED" "$ALIGNED"

          "$ANDROID_HOME/build-tools/34.0.0/apksigner" sign \
            --ks keystore.jks \
            --ks-key-alias "$KEY_ALIAS" \
            --ks-pass pass:"$KEYSTORE_PASSWORD" \
            --key-pass pass:"$KEY_PASSWORD" \
            --out "$SIGNED" \
            "$ALIGNED"

          "$ANDROID_HOME/build-tools/34.0.0/apksigner" verify --print-certs "$SIGNED"
          echo "SIGNED_APK=$SIGNED" >> $GITHUB_ENV

      # ---------- Pubblica artefatto ----------
      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: Plutoo-APK-signed
          path: ${{ env.SIGNED_APK }}
          if-no-files-found: error
